[package]
name = "compute-rust-auth"
version = "0.3.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "0.9.1"
hmac-sha256 = "1.1.6"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.82"
base64 = "0.21.0"
toml = "0.5.9"
jwt-simple = "0.11.3"
