authors = ["<oss@fastly.com>"]
description = "Connect to an identity provider such as Auth0 using OAuth 2.0 and validate authentication status at the Edge, to authorize access to your edge or origin hosted applications."
language = "rust"
name = "compute-rust-auth"
manifest_version = 2

[setup]

  [setup.backends]

    [setup.backends.backend]
      description = "Content or application origin"
      address = "httpbin.org"

    [setup.backends.idp]
      description = "Identity provider authorization server"
      address = "dev-xxxxxxxxx.us.auth0.com"
